---
development:
  cloud_name: fliardet
  api_key: '748349891643778'
  api_secret: xcoc29Rx3cibYwf24zNnadfl4vM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: fliardet
  api_key: '748349891643778'
  api_secret: xcoc29Rx3cibYwf24zNnadfl4vM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: fliardet
  api_key: '748349891643778'
  api_secret: xcoc29Rx3cibYwf24zNnadfl4vM
  enhance_image_tag: true
  static_image_support: false
